import { useEffect, useMemo, useState } from 'react';
import { LanguageContext, type Language, type LanguageContextType } from './languageCore';

const STORAGE_KEY = 'domiz-language';

const translations: Record<Language, Record<string, string>> = {
    pl: {
        'nav.home': 'Strona główna',
        'nav.offers': 'Oferty',
        'nav.osiedle': 'Osiedle Tłuszcz',
        'nav.calculators': 'Kalkulatory',
        'nav.blog': 'Blog',
        'nav.smartHome': 'Smart Home',
        'nav.more': 'Więcej',
        'nav.favorites': 'Ulubione',
        'nav.addProperty': 'Sprzedaj nieruchomość',
        'nav.call': 'Zadzwoń',
        'header.favoritesTitle': 'Ulubione',
        'header.toggleMenu': 'Przełącz menu',
        'header.mobileMenuLabel': 'Menu nawigacji',

        'hero.badge': 'Nowoczesne Nieruchomości',
        'hero.titleTop': 'Biuro Nieruchomości',
        'hero.subtitle': 'Sprzedaż, kupno i wynajem domów, mieszkań oraz działek w Tłuszczu i powiecie wołomińskim. Twój zaufany partner na rynku nieruchomości.',
        'hero.browse': 'Przeglądaj Oferty',
        'hero.sell': 'Sprzedaj Nieruchomość',
        'hero.offers': 'Ofert',
        'hero.sold': 'Sprzedanych',
        'hero.experience': 'Lata doświadczenia',
        'hero.searchTitle': 'Szybkie Wyszukiwanie',
        'hero.locationLabel': 'Lokalizacja lub nazwa',
        'hero.locationPlaceholder': 'Wpisz miasto, ulicę...',
        'hero.type': 'Typ',
        'hero.maxPrice': 'Cena do',
        'hero.search': 'Szukaj',
        'hero.mediaBadge': 'Osiedle Tłuszcz – nowe domy',

        'common.any': 'Dowolna',
        'common.all': 'Wszystkie',
        'common.house': 'Dom',
        'common.houses': 'Domy',
        'common.apartment': 'Mieszkanie',
        'common.apartments': 'Mieszkania',
        'common.land': 'Działka',
        'common.plots': 'Działki',
        'common.loading': 'Ładowanie...',
        'common.forSale': 'Na Sprzedaż',
        'common.forRent': 'Wynajem',
        'common.featured': 'Wyróżniona',
        'common.details': 'Zobacz Szczegóły',
        'common.removeFavorite': 'Usuń z ulubionych',
        'common.addFavorite': 'Dodaj do ulubionych',
        'common.month': 'mies.',

        'home.whyLabel': 'Dlaczego my',
        'home.whyTitlePrefix': 'Dlaczego',
        'home.whyDesc': 'Oferujemy kompleksowe wsparcie na każdym etapie transakcji. Zaufaj ekspertom z wieloletnim doświadczeniem.',
        'home.feature1Title': 'Premium Standard',
        'home.feature1Desc': 'Tylko zweryfikowane i sprawdzone nieruchomości w najlepszych lokalizacjach.',
        'home.feature2Title': 'Bezpieczna Transakcja',
        'home.feature2Desc': 'Pełna opieka prawna nad każdym etapem zakupu i sprzedaży.',
        'home.feature3Title': 'Oszczędność Czasu',
        'home.feature3Desc': 'Dopasujemy oferty idealnie do Twoich potrzeb i możliwości.',
        'home.processLabel': 'Proces',
        'home.processTitlePrefix': 'Jak',
        'home.processTitleHighlight': 'pracujemy',
        'home.processDesc': 'Cztery proste kroki od pierwszej rozmowy do przekazania kluczy.',
        'home.step1Title': 'Kontakt',
        'home.step1Desc': 'Opowiedz nam o swoich potrzebach - umówimy bezpłatną konsultację.',
        'home.step2Title': 'Wycena i oferty',
        'home.step2Desc': 'Przygotujemy wycenę nieruchomości lub dobierzemy oferty pod Twoje kryteria.',
        'home.step3Title': 'Wizyta i negocjacje',
        'home.step3Desc': 'Zorganizujemy zwiedzanie obiektów i poprowadzimy negocjacje.',
        'home.step4Title': 'Umowa i odbiór',
        'home.step4Desc': 'Zapewnimy opiekę prawną, podpisanie umowy i przekazanie kluczy.',
        'home.reviewsLabel': 'Opinie',
        'home.reviewsTitle': 'Zaufali',
        'home.reviewsHighlight': 'nam',
        'home.reviewsSuffix': 'klienci',
        'home.testimonial1': 'Profesjonalna obsługa od początku do końca. Znaleźliśmy wymarzony dom w Tłuszczu w 2 miesiące.',
        'home.testimonial2': 'Polecam! Transparentna wycena, pomoc prawna i pełne zaangażowanie. Naprawdę warto.',
        'home.testimonial3': 'Dziękujemy za cierpliwość i pomoc w wyborze mieszkania. Świetny kontakt i terminowość.',
        'home.clientLabel': 'Klient Domiz Homes',
        'home.offerLabel': 'Oferta',
        'home.featuredProperties': 'Wyróżnione Nieruchomości',
        'home.offerDesc': 'Wybrane domy, mieszkania i działki z naszej aktualnej oferty w Tłuszczu i okolicach.',
        'home.offersEmptyTitle': 'Przygotowujemy nowe oferty',
        'home.offersEmptyDesc': 'W tej chwili nie mamy wyróżnionych nieruchomości. Zobacz pełną listę ofert lub napisz do nas – znajdziemy nieruchomość pod Twoje kryteria.',
        'home.seeAll': 'Zobacz wszystkie',
        'home.ctaTitle': 'Gotowy na zmianę adresu?',
        'home.ctaDesc': 'Skontaktuj się z nami już dziś. Pomożemy Ci znaleźć Twój wymarzony nowy dom.',
        'home.contactUs': 'Skontaktuj się z nami',
        'home.seeCalculators': 'Zobacz kalkulatory',
        'home.trust1': 'Bezpłatna wycena',
        'home.trust2': 'Doradztwo na każdym etapie',
        'home.trust3': 'Obsługa prawna',

        'properties.breadcrumb': 'Oferty',
        'properties.title': 'Oferty Nieruchomości',
        'properties.subtitle': 'Znajdź swój wymarzony dom lub mieszkanie w Tłuszczu i okolicach',
        'properties.searchPlaceholder': 'Szukaj po nazwie lub lokalizacji...',
        'properties.filters': 'Filtry',
        'properties.typeLabel': 'Typ nieruchomości',
        'properties.status': 'Status',
        'properties.forSale': 'Na sprzedaż',
        'properties.forRent': 'Do wynajęcia',
        'properties.priceTo': 'Cena do',
        'properties.clear': 'Wyczyść',
        'properties.foundPrefix': 'Znaleziono',
        'properties.foundSuffix': 'ofert',
        'properties.emptyTitle': 'Nie znaleziono ofert',
        'properties.emptyDesc': 'Nie znaleziono ofert spełniających kryteria wyszukiwania.',
        'properties.clearFilters': 'Wyczyść filtry',
        'properties.loadingTitle': 'Ładujemy oferty',
        'properties.loadingDesc': 'Pobieramy aktualne nieruchomości i zdjęcia.',

        'favorites.title': 'Ulubione oferty',
        'favorites.emptyLead': 'Nie masz jeszcze zapisanych ofert. Kliknij serduszko na kartach nieruchomości, aby dodać je tutaj.',
        'favorites.countSingle': 'Masz 1 zapisaną ofertę.',
        'favorites.countManyPrefix': 'Masz',
        'favorites.countManySuffix': 'zapisanych ofert.',
        'favorites.emptyDesc': 'Twoje ulubione oferty pojawią się tutaj po dodaniu ich na stronie ofert.',
        'favorites.browse': 'Przeglądaj oferty',

        'footer.desc': 'Tworzymy przyszłość nieruchomości. Nowoczesne podejście do sprzedaży, kupna i wynajmu Twojego wymarzonego domu.',
        'footer.navigation': 'Nawigacja',
        'footer.allOffers': 'Wszystkie oferty',
        'footer.housesForSale': 'Domy na sprzedaż',
        'footer.offersTluszcz': 'Oferty w Tłuszczu',
        'footer.contact': 'Kontakt',
        'footer.services': 'Usługi',
        'footer.buyProperty': 'Kupno nieruchomości',
        'footer.sellProperty': 'Sprzedaż nieruchomości',
        'footer.financing': 'Finansowanie i kalkulatory',
        'footer.contactForm': 'Formularz kontaktowy',
        'footer.rights': 'Wszelkie prawa zastrzeżone.',

        'addProperty.label': 'Sprzedaj nieruchomość',
        'addProperty.successTitle': 'Dziękujemy za zgłoszenie!',
        'addProperty.successDesc': 'Twoje zgłoszenie zostało wysłane do weryfikacji. Skontaktujemy się z Tobą w ciągu 24 godzin, aby omówić szczegóły.',
        'addProperty.home': 'Strona główna',
        'addProperty.addAnother': 'Dodaj kolejną',
        'addProperty.heroTitlePrefix': 'Sprzedaj z',
        'addProperty.heroDesc': 'Wypełnij formularz, a nasz agent skontaktuje się z Tobą w ciągu 24h. Przygotujemy profesjonalne ogłoszenie i pomożemy w sprzedaży.',

        'property.notFound': 'Nie znaleziono oferty',
        'property.backToOffers': 'Wróć do listy ofert',
    },
    en: {
        'nav.home': 'Home',
        'nav.offers': 'Listings',
        'nav.osiedle': 'Tluszcz Estate',
        'nav.calculators': 'Calculators',
        'nav.blog': 'Blog',
        'nav.smartHome': 'Smart Home',
        'nav.more': 'More',
        'nav.favorites': 'Favorites',
        'nav.addProperty': 'Sell property',
        'nav.call': 'Call',
        'header.favoritesTitle': 'Favorites',
        'header.toggleMenu': 'Toggle menu',
        'header.mobileMenuLabel': 'Navigation menu',

        'hero.badge': 'Modern Real Estate',
        'hero.titleTop': 'Real Estate Agency',
        'hero.subtitle': 'Sales, purchases and rentals of houses, apartments and land in Tluszcz and the Wolomin district. Your trusted partner in real estate.',
        'hero.browse': 'Browse Listings',
        'hero.sell': 'Sell Property',
        'hero.offers': 'Listings',
        'hero.sold': 'Sold',
        'hero.experience': 'Years of experience',
        'hero.searchTitle': 'Quick Search',
        'hero.locationLabel': 'Location or name',
        'hero.locationPlaceholder': 'Enter city, street...',
        'hero.type': 'Type',
        'hero.maxPrice': 'Price up to',
        'hero.search': 'Search',
        'hero.mediaBadge': 'Tluszcz Estate – new homes',

        'common.any': 'Any',
        'common.all': 'All',
        'common.house': 'House',
        'common.houses': 'Houses',
        'common.apartment': 'Apartment',
        'common.apartments': 'Apartments',
        'common.land': 'Land',
        'common.plots': 'Plots',
        'common.loading': 'Loading...',
        'common.forSale': 'For Sale',
        'common.forRent': 'For Rent',
        'common.featured': 'Featured',
        'common.details': 'View Details',
        'common.removeFavorite': 'Remove from favorites',
        'common.addFavorite': 'Add to favorites',
        'common.month': 'mo.',

        'home.whyLabel': 'Why us',
        'home.whyTitlePrefix': 'Why',
        'home.whyDesc': 'We provide complete support at every stage of the transaction. Work with experts backed by years of experience.',
        'home.feature1Title': 'Premium Standard',
        'home.feature1Desc': 'Only verified and carefully checked properties in top locations.',
        'home.feature2Title': 'Secure Transaction',
        'home.feature2Desc': 'Full legal support through every stage of buying and selling.',
        'home.feature3Title': 'Save Time',
        'home.feature3Desc': 'We match listings precisely to your needs and budget.',
        'home.processLabel': 'Process',
        'home.processTitlePrefix': 'How we',
        'home.processTitleHighlight': 'work',
        'home.processDesc': 'Four simple steps from the first conversation to the key handover.',
        'home.step1Title': 'Contact',
        'home.step1Desc': 'Tell us what you need - we will arrange a free consultation.',
        'home.step2Title': 'Valuation and offers',
        'home.step2Desc': 'We prepare a property valuation or select listings that match your criteria.',
        'home.step3Title': 'Viewing and negotiation',
        'home.step3Desc': 'We organize viewings and lead the negotiation process.',
        'home.step4Title': 'Contract and handover',
        'home.step4Desc': 'We provide legal support, contract signing and key handover.',
        'home.reviewsLabel': 'Reviews',
        'home.reviewsTitle': 'Clients',
        'home.reviewsHighlight': 'trust',
        'home.reviewsSuffix': 'us',
        'home.testimonial1': 'Professional service from start to finish. We found our dream home in Tluszcz in two months.',
        'home.testimonial2': 'Highly recommended. Transparent valuation, legal support and real commitment throughout.',
        'home.testimonial3': 'Thank you for your patience and help choosing an apartment. Great communication and punctuality.',
        'home.clientLabel': 'Domiz Homes client',
        'home.offerLabel': 'Listings',
        'home.featuredProperties': 'Featured Properties',
        'home.offerDesc': 'Selected houses, apartments and land from our current portfolio in Tluszcz and the surrounding area.',
        'home.offersEmptyTitle': 'New listings on the way',
        'home.offersEmptyDesc': 'We have no featured properties right now. Browse the full list of listings or message us - we will find a property that matches your criteria.',
        'home.seeAll': 'See all',
        'home.ctaTitle': 'Ready for a new address?',
        'home.ctaDesc': 'Contact us today. We will help you find your dream new home.',
        'home.contactUs': 'Contact us',
        'home.seeCalculators': 'View calculators',
        'home.trust1': 'Free valuation',
        'home.trust2': 'Guidance at every stage',
        'home.trust3': 'Legal support',

        'properties.breadcrumb': 'Listings',
        'properties.title': 'Property Listings',
        'properties.subtitle': 'Find your dream house or apartment in Tluszcz and the surrounding area',
        'properties.searchPlaceholder': 'Search by name or location...',
        'properties.filters': 'Filters',
        'properties.typeLabel': 'Property type',
        'properties.status': 'Status',
        'properties.forSale': 'For sale',
        'properties.forRent': 'For rent',
        'properties.priceTo': 'Price up to',
        'properties.clear': 'Clear',
        'properties.foundPrefix': 'Found',
        'properties.foundSuffix': 'listings',
        'properties.emptyTitle': 'No listings found',
        'properties.emptyDesc': 'No listings match your search criteria.',
        'properties.clearFilters': 'Clear filters',
        'properties.loadingTitle': 'Loading listings',
        'properties.loadingDesc': 'Fetching current properties and photos.',

        'favorites.title': 'Favorite listings',
        'favorites.emptyLead': 'You have not saved any listings yet. Click the heart on property cards to add them here.',
        'favorites.countSingle': 'You have 1 saved listing.',
        'favorites.countManyPrefix': 'You have',
        'favorites.countManySuffix': 'saved listings.',
        'favorites.emptyDesc': 'Your favorite listings will appear here after you add them from the listings page.',
        'favorites.browse': 'Browse listings',

        'footer.desc': 'We are shaping the future of real estate with a modern approach to selling, buying and renting your dream home.',
        'footer.navigation': 'Navigation',
        'footer.allOffers': 'All listings',
        'footer.housesForSale': 'Houses for sale',
        'footer.offersTluszcz': 'Listings in Tluszcz',
        'footer.contact': 'Contact',
        'footer.services': 'Services',
        'footer.buyProperty': 'Buying property',
        'footer.sellProperty': 'Selling property',
        'footer.financing': 'Financing and calculators',
        'footer.contactForm': 'Contact form',
        'footer.rights': 'All rights reserved.',

        'addProperty.label': 'Sell property',
        'addProperty.successTitle': 'Thank you for your submission!',
        'addProperty.successDesc': 'Your request has been sent for review. We will contact you within 24 hours to discuss the details.',
        'addProperty.home': 'Home',
        'addProperty.addAnother': 'Add another',
        'addProperty.heroTitlePrefix': 'Sell with',
        'addProperty.heroDesc': 'Fill out the form and our agent will contact you within 24 hours. We will prepare a professional listing and help you sell.',

        'property.notFound': 'Listing not found',
        'property.backToOffers': 'Back to listings',
    },
};

function getInitialLanguage(): Language {
    if (typeof window === 'undefined') return 'pl';
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved === 'en' ? 'en' : 'pl';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>(getInitialLanguage);

    const setLanguage = (nextLanguage: Language) => {
        setLanguageState(nextLanguage);
        localStorage.setItem(STORAGE_KEY, nextLanguage);
    };

    useEffect(() => {
        document.documentElement.lang = language;
    }, [language]);

    const value = useMemo<LanguageContextType>(() => ({
        language,
        setLanguage,
        toggleLanguage: () => setLanguage(language === 'pl' ? 'en' : 'pl'),
        t: (key: string) => translations[language][key] ?? translations.pl[key] ?? key,
    }), [language]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}
